### ISSUE TITLE
naming convention for the paired data

### ISSUE THREAD

**Issue by devraj89** [Blade6570/Learningimage-to-imagetranslationusingpairedandunpairedtrainingsamples#1]
Hi
Thanks for your nice work!
Can you please specify how to put up the paired data in the train sub-folder?
Any specific naming convention that we should follow? like image_a_1, image_a_2, image_b_1, image_b_2, ... etc ?

Any suggestions will be helpful for running the code.

Thanks
Devraj

**Comment by Blade6570** [comment]
Hi, 
In the dataset folder, I have kept a folder under the name of "train". It is for paired data (Where the image and its map are concatenated and named as i.jpg where i=1:50). For the unpaired data the folders are "trainA" and "trainB". You can give the same name for the image and its map and keep it in the separate folder as given in the dataset folder. 

Thanks
