### ISSUE TITLE
Where is the adversarial consistency loss?

### ISSUE THREAD

**Issue by m-birke** [Blade6570/Learningimage-to-imagetranslationusingpairedandunpairedtrainingsamples#4]
Hello Mr. Tripathy,

I'm sorry if I overlooked it, but I can't find a model using the conditional discriminator for the adversarial consistency loss nor an implementation of it.

Greetings

**Comment by Blade6570** [comment]
Hi, 

I think the part you are looking for is [here](https://github.com/Blade6570/Learningimage-to-imagetranslationusingpairedandunpairedtrainingsamples/blob/4bf360f83d32d4473f37ef252f92f83711b1127e/models/cycle_gan_model.py#L144).

The `def backward_D_C` and `def backward_D_D` functions are used for this purpose. 

BW,
Soumya
